name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: src
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup MinVer
        run: |
          dotnet tool install --global minver-cli --version 4.2.0

      - name: Calculate Version
        run: |
          echo "MINVERVERSIONOVERRIDE=$($HOME/.dotnet/tools/minver -t v. -m 1.0 -d preview)" >> $GITHUB_ENV
      
      - name: Calculated Version
        run: |
          echo "${{ env.MINVERVERSIONOVERRIDE }}"

      - name: Build
        run: dotnet publish -c Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: azqr-${{ matrix.os }}
          path: ./src/azqr/bin/Release/net6.0/publish/
